<?php
/**
 * @category  Burdz
 * @package   Burdz\Offerz
 * @author    David Buros <david.buros@gmail.com>
 * @licence   The Unlicense
 */
$offers = $block->getViewModel()->getCurrentOffers();
?>
<?php if($offers->getTotalCount() > 0):?>
    <?php foreach($offers->getItems() as $offer):?>
        <h1><?php echo $offer->getLabel();?></h1>
        <img src="<?php echo $block->getViewModel()->getImageUrl($offer->getImage());?>" width="100%" />
    <?php endforeach?>
<?php endif?>

