<?php
/**
 * @category  Burdz
 * @package   Burdz\Offerz
 * @author    David Buros <david.buros@gmail.com>
 * @licence   The Unlicense
 */
$offers = $block->getViewModel()->getCurrentOffers();
?>
<?php if($offers->getTotalCount() > 0):?>
    <?php foreach($offers->getItems() as $offer):?>
        <div id="category-offer-<?php echo $offer->getId();?>" class="category-offer">
            <img src="<?php echo $block->getViewModel()->getImageUrl($offer->getImage());?>" alt="<?php echo $offer->getLabel();?>"/>
            <div class="cta primary">
                <a href="<?php echo $offer->getLink();?>" target="_blank" class="action create primary">
                    <span><?php echo __('Click to discover this offer');?></span>
                </a>
            </div>
        </div>
    <?php endforeach?>
<?php endif?>

